language: node_js
node_js:
  - '5'
  - '4'
notifications:
  slack:
    secure: g1/FYVSC3a6b8fL/wazTa5rlG9Kpz6TDesIYEXolfNeaAtkzVXaRiT5tP87X6kI+yXoCvQMn/QMqfCuwZ3Sl3IFVKSwXiGaRy6bwePM6hAcga4HumQlmm8X9c4LaMWroeU+6XzFiLOpCqdabsgOcnLyoeqRhXAjVrEgP+Zoss4YJcrcTZWDmzeajbRN2dDR8rW+z4kVgRIXUo91Z9n3+AOi1PU+L/rYMK+BeuHG46SSIvaF32Qa9klPlSdtIwCLQsFn/zv5YxbBLbyqXE7LaCWU9TcQy/gdOpNAsSgsJJxaqwT7zEVNq2uCdY0poD1TamZh+sjnk/iNaPfK47chqzMaJ83TxDCQ2nncea5HuCn69QCNTeY19R6WhM8mpXSqCCU2znf4wkYwrzrLwAiUcCkDM+4HOjAxaY+bf/ClSA5N0P9jPsPbqcWblbU2JOVx/KlMmPB7mK/LuGCwNsi+xtz8ZftFUk5DVzkJgX7W7W/MpCMrsC8r38yLvRM8bozu8Eal7P5KpPVQDCLPvP+4cduemtGd03BZ7XDMWP6YxyRXuw+iDb0ey8Je81iPVPbZRarTU7adbVIbXS3yBigccxIW1f5JoTtkImlPYKihn6g/jaFffAY+dg0nI0Bisij3s56w3UbSLQzMutwNXEHvrye7eLmzvP5103AGjRyBgbYU=
