import { keyPos } from '$services/keyPos';
import Key from './Key';

export default {
  [keyPos.ESCAPE]: new Key([], ['Esc']),
  [keyPos.F1]: new Key([], ['F1']),
  [keyPos.F2]: new Key([], ['F2']),
  [keyPos.F3]: new Key([], ['F3']),
  [keyPos.F4]: new Key([], ['F4']),
  [keyPos.F5]: new Key([], ['F5']),
  [keyPos.F6]: new Key([], ['F6']),
  [keyPos.F7]: new Key([], ['F7']),
  [keyPos.F8]: new Key([], ['F8']),
  [keyPos.F9]: new Key([], ['F9']),
  [keyPos.F10]: new Key([], ['F10']),
  [keyPos.F11]: new Key([], ['F11']),
  [keyPos.F12]: new Key([], ['F12']),
  [keyPos.POWER]: new Key([], ['']),
  [keyPos.BACKQUOTE]: new Key(['~', '`']),
  [keyPos.DIGIT1]: new Key(['1', '!']),
  [keyPos.DIGIT2]: new Key(['2', '@']),
  [keyPos.DIGIT3]: new Key(['3', '#']),
  [keyPos.DIGIT4]: new Key(['4', '$']),
  [keyPos.DIGIT5]: new Key(['5', '%']),
  [keyPos.DIGIT6]: new Key(['6', '^']),
  [keyPos.DIGIT7]: new Key(['7', '&']),
  [keyPos.DIGIT8]: new Key(['8', '*']),
  [keyPos.DIGIT9]: new Key(['9', '(']),
  [keyPos.DIGIT0]: new Key(['0', ')']),
  [keyPos.MINUS]: new Key(['-', '_']),
  [keyPos.EQUAL]: new Key(['=', '+']),
  [keyPos.BACKSPACE]: new Key([], ['Delete'], { size: 1.5 }),
  [keyPos.TAB]: new Key([], ['Tab'], { size: 1.5 }),
  [keyPos.KEY_Q]: new Key(['q', 'Q'], ['Q']),
  [keyPos.KEY_W]: new Key(['w', 'W'], ['W']),
  [keyPos.KEY_E]: new Key(['e', 'E'], ['E']),
  [keyPos.KEY_R]: new Key(['r', 'R'], ['R']),
  [keyPos.KEY_T]: new Key(['t', 'T'], ['T']),
  [keyPos.KEY_Y]: new Key(['y', 'Y'], ['Y']),
  [keyPos.KEY_U]: new Key(['u', 'U'], ['U']),
  [keyPos.KEY_I]: new Key(['i', 'I'], ['I']),
  [keyPos.KEY_O]: new Key(['o', 'O'], ['O']),
  [keyPos.KEY_P]: new Key(['p', 'P'], ['P']),
  [keyPos.BRACKET_LEFT]: new Key(['[', '{']),
  [keyPos.BRACKET_RIGHT]: new Key([']', '}']),
  [keyPos.INTL_YEN]: new Key(['\\', '|']),
  [keyPos.CONTROL_LEFT]: new Key([], ['Ctrl'], { size: 1.8 }),
  [keyPos.KEY_A]: new Key(['a', 'A'], ['A']),
  [keyPos.KEY_S]: new Key(['s', 'S'], ['S']),
  [keyPos.KEY_D]: new Key(['d', 'D'], ['D']),
  [keyPos.KEY_F]: new Key(['f', 'F'], ['F']),
  [keyPos.KEY_G]: new Key(['g', 'G'], ['G']),
  [keyPos.KEY_H]: new Key(['h', 'H'], ['H']),
  [keyPos.KEY_J]: new Key(['j', 'J'], ['J']),
  [keyPos.KEY_K]: new Key(['k', 'K'], ['K']),
  [keyPos.KEY_L]: new Key(['l', 'L'], ['L']),
  [keyPos.SEMICOLON]: new Key([';', ':']),
  [keyPos.QUOTE]: new Key(['\'', '"']),
  [keyPos.ENTER]: new Key([], ['Enter'], { size: 2.2 }),
  [keyPos.SHIFT_LEFT]: new Key([], ['Shift'], { size: 2.5 }),
  [keyPos.KEY_Z]: new Key(['z', 'Z'], ['Z']),
  [keyPos.KEY_X]: new Key(['x', 'X'], ['X']),
  [keyPos.KEY_C]: new Key(['c', 'C'], ['C']),
  [keyPos.KEY_V]: new Key(['v', 'V'], ['V']),
  [keyPos.KEY_B]: new Key(['b', 'B'], ['B']),
  [keyPos.KEY_N]: new Key(['n', 'N'], ['N']),
  [keyPos.KEY_M]: new Key(['m', 'M'], ['M']),
  [keyPos.COMMA]: new Key([',', '<']),
  [keyPos.PERIOD]: new Key(['.', '>']),
  [keyPos.SLASH]: new Key(['/', '?']),
  [keyPos.SHIFT_RIGHT]: new Key([], ['Shift'], { size: 2.5 }),
  [keyPos.CAPS_LOCK]: new Key([], ['Caps']),
  [keyPos.ALT_LEFT]: new Key([], ['Alt']),
  [keyPos.OS_LEFT]: new Key([], ['Command']),
  [keyPos.SPACE]: new Key([], [''], { size: 3.3 }),
  [keyPos.OS_RIGHT]: new Key([], ['Command']),
  [keyPos.ALT_RIGHT]: new Key([], ['Alt']),
  [keyPos.FUNCTION]: new Key([], ['Fn'])
};

