import { keyPos } from '$services/keyPos';
import Key from './Key';

export default {
  [keyPos.DIGIT1]: new Key(['1', '!']),
  [keyPos.DIGIT2]: new Key(['2', '"']),
  [keyPos.DIGIT3]: new Key(['3', '#']),
  [keyPos.DIGIT4]: new Key(['4', '$']),
  [keyPos.DIGIT5]: new Key(['5', '%']),
  [keyPos.DIGIT6]: new Key(['6', '&']),
  [keyPos.DIGIT7]: new Key(['7', '\'']),
  [keyPos.DIGIT8]: new Key(['8', '(']),
  [keyPos.DIGIT9]: new Key(['9', ')']),
  [keyPos.DIGIT0]: new Key(['0', '']),
  [keyPos.MINUS]: new Key(['-', '=']),
  [keyPos.EQUAL]: new Key(['^', '~']),
  [keyPos.INTL_YEN]: new Key(['\\', '|']),
  [keyPos.KEY_Q]: new Key(['q', 'Q'], ['Q']),
  [keyPos.KEY_W]: new Key(['w', 'W'], ['W']),
  [keyPos.KEY_E]: new Key(['e', 'E'], ['E']),
  [keyPos.KEY_R]: new Key(['r', 'R'], ['R']),
  [keyPos.KEY_T]: new Key(['t', 'T'], ['T']),
  [keyPos.KEY_Y]: new Key(['y', 'Y'], ['Y']),
  [keyPos.KEY_U]: new Key(['u', 'U'], ['U']),
  [keyPos.KEY_I]: new Key(['i', 'I'], ['I']),
  [keyPos.KEY_O]: new Key(['o', 'O'], ['O']),
  [keyPos.KEY_P]: new Key(['p', 'P'], ['P']),
  [keyPos.BRACKET_LEFT]: new Key(['@', '`']),
  [keyPos.BRACKET_RIGHT]: new Key(['[', '{']),
  [keyPos.KEY_A]: new Key(['a', 'A'], ['A']),
  [keyPos.KEY_S]: new Key(['s', 'S'], ['S']),
  [keyPos.KEY_D]: new Key(['d', 'D'], ['D']),
  [keyPos.KEY_F]: new Key(['f', 'F'], ['F']),
  [keyPos.KEY_G]: new Key(['g', 'G'], ['G']),
  [keyPos.KEY_H]: new Key(['h', 'H'], ['H']),
  [keyPos.KEY_J]: new Key(['j', 'J'], ['J']),
  [keyPos.KEY_K]: new Key(['k', 'K'], ['K']),
  [keyPos.KEY_L]: new Key(['l', 'L'], ['L']),
  [keyPos.SEMICOLON]: new Key([';', '+']),
  [keyPos.QUOTE]: new Key([':', '*']),
  [keyPos.KEY_Z]: new Key(['z', 'Z'], ['Z']),
  [keyPos.KEY_X]: new Key(['x', 'X'], ['X']),
  [keyPos.KEY_C]: new Key(['c', 'C'], ['C']),
  [keyPos.KEY_V]: new Key(['v', 'V'], ['V']),
  [keyPos.KEY_B]: new Key(['b', 'B'], ['B']),
  [keyPos.KEY_N]: new Key(['n', 'N'], ['N']),
  [keyPos.KEY_M]: new Key(['m', 'M'], ['M']),
  [keyPos.COMMA]: new Key([',', '<']),
  [keyPos.PERIOD]: new Key(['.', '>']),
  [keyPos.SLASH]: new Key(['/', '?'])
};

